//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryQussia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Client_ID { get; set; }
        public string full_name { get; set; }
        public string phone_number { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<double> cash { get; set; }
        public Nullable<int> points { get; set; }
        public Nullable<bool> block { get; set; }
    }
}
