//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryQussia
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Image
    {
        [DataMember]
        public int Img_ID { get; set; }
        [DataMember]
        public string Image_Path { get; set; }
        [DataMember]
        public Nullable<int> Item_ID { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
