//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryQussia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Images = new HashSet<Image>();
            this.Genders = new HashSet<Gender>();
        }
    
        public int Item_ID { get; set; }
        public string Item_Name { get; set; }
        public string Item_Desc { get; set; }
        public double Item_Price { get; set; }
        public bool Approval { get; set; }
        public Nullable<double> Percent { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<bool> Offer { get; set; }
        public Nullable<int> Cat_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Type_ID { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        public virtual Type Type { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gender> Genders { get; set; }
    }
}
